---
default_tools: ["standardrb", "rubocop", "markdown_lint", "rspec"]
executor: concurrent
comparison_branch: main
changed_files: false
filter_messages: false
logging: light
colorize: true
message_format: "%lcyan10tool| [%myellow40rule] %bred60loc  %e-90body"
