---
AllCops:
  SuggestExtensions: false
  DisabledByDefault: true

Metrics/AbcSize:
  Max: 15
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/PerceivedComplexity:
  Max: 7

Metrics/ClassLength:
  CountComments: false
  Max: 150
Metrics/MethodLength:
  CountComments: false
  Max: 15
Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true
