name: RSpec

on: [push]

jobs:
  RSpec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2', 'head']

    steps:
      - uses: actions/checkout@v3

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Cache gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-rspec-${{ matrix.ruby-version }}-${{ hashFiles('Gemfile.lock') }}
          restore-keys:
            ${{ runner.os }}-rspec-${{ matrix.ruby-version }}-

      - name: Install gems
        run: bundle install --jobs 4 --retry 3

      - name: Run RSpec
        run: SIMPLECOV=true SIMPLECOV_TEXT=true bundle exec rspec
